### ISSUE TITLE
[Question] Chapin 1987 - spatial orientation & 

### ISSUE THREAD

**Issue by sdalla** [Cortical-Plasticity-Lab/Solenoid-Ephys-Analyses#10]
In the figures (such as fig 1) what is the spatial orientation? Which direction is Anterior/posterior which direction is medial/distal etc what is the plane we have a 'slice' of?

What is tangential slice vs vertical slice of layer IV?

Which of their claims is most relevant to the ephys experiment? "Neurons in the PGZ but not DZ respond to cutaneous stimulation in anesthetized rats", for example?

**Comment by m053m716** [comment]
@sdalla 
### Re: Spatial Orientation ###
For figure 1 it's a flattened cortex, so at the bottom M refers to medial and at the right, C refers to Caudal which is toward the back of the skull (Rostral towards the front/whiskers). So a tangential slice refers to a transverse plane that lets you see the layout as you might look at it from above the skull during surgery, whereas a vertical slice would be like a coronal section so you can see the depth of everything.

### Re: Claims ###
Fig. 14 gives a good overview as a starting point for what we know about S1 cortico-cortical connections, so what is plausible in terms of the existing circuitry there and how that might connect up. There's another Sievert paper that describes unit receptive fields in motor areas (Figure 5 of 1985 paper attached). Figure 2 of the Chapin 1986 paper is kind of a nice visualization of the relation between cutaneous receptive field and laminar distribution (cortical layer).

[Sievert and Neafsey - 1985 - Chronic Unit Study of the Sensory Properties of Neurons in the Forelimb Areas of Rat Sensorimotor Cortex.pdf](https://github.com/Cortical-Plasticity-Lab/Solenoid-Ephys-Analyses/files/4795046/Sievert.and.Neafsey.-.1985.-.Chronic.Unit.Study.of.the.Sensory.Properties.of.Neurons.in.the.Forelimb.Areas.of.Rat.Sensorimotor.Cortex.pdf)

[Chapin and Woodward - 1986 - Distribution of somatic sensory and active-movement neuronal discharge properties in the MI-SI cortical border area in the rat.pdf](https://github.com/Cortical-Plasticity-Lab/Solenoid-Ephys-Analyses/files/4795029/Chapin.and.Woodward.-.1986.-.Distribution.of.somatic.sensory.and.active-movement.neuronal.discharge.properties.in.the.MI-SI.cortical.border.area.in.the.rat.pdf)
