### ISSUE TITLE
[Question] R19-227 Probe A Depth (handwriting)

### ISSUE THREAD

**Issue by sdalla** [Cortical-Plasticity-Lab/Solenoid-Ephys-Analyses#11]
Cant tell if R19-227 (MMT2) probe A depth is 1605 or 1805. Based off of the notes I believe its 1605 and put it as that. 

Similar situation with R19-230 (MM-U1) - I think probe A is 1807 here.

**Comment by m053m716** [comment]
T2 - Most-likely 1605
U1 - Yep, definitely 1807
