### ISSUE TITLE
Would BlockID be redundant info for ICMS site data?

### ISSUE THREAD

**Issue by sdalla** [Cortical-Plasticity-Lab/Solenoid-Ephys-Analyses#12]
It seems like the ICMS site data is just done once before all the block are done for an experiment. therefore it seems like it doesnt need a BlockID rather it just need animalID + date 'R19-226_2019_11_05' like so. Maybe I am not understanding, though.

**Comment by m053m716** [comment]
Yep you're right, ICMS sites should be parsed at the `solRat` level so those would actually just need the AnimalID. Since the ICMS preparations are terminal that means they only have ICMS on a single date anyways so they don't even need Date, just AnimalID.
