### ISSUE TITLE
Why are all AP values in Probe-Info positive?

### ISSUE THREAD

**Issue by sdalla** [Cortical-Plasticity-Lab/Solenoid-Ephys-Analyses#14]
Was looking back at Probe-Info to double check the +/- convention and found that all the AP are positive. Wasnt sure if this was on purpose or accidental? I remember some debate about which direction was positive and which was negative. For ICMS-Info should I just leave AP and ML as positive numbers?

**Comment by m053m716** [comment]
@sdalla 
Just to note, the relative AP coordinate makes it easy to see how rotating that grid even just a little bit to get it more "centered" with respect to Bregma and midline can actually cause the apparent coordinates to change a fair bit.

* **RFA**. This area is rostral (anterior) so it should be positive (always).
* **S1**. This area should be near zero or *negative* for AP distance from bregma. I don't have all the S1 sites having a positive value for the AP coordinate so hopefully the Git-LFS is updating the common shared version correctly.
